stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - 'mvn clean package -DskipTests -e'
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  stage: deploy
  script:
    - 'pwd'
    - "(ps aux | grep demo | grep -v grep | awk '{print $2}' | xargs -r kill) || true"
    - "cp target/demo-0.0.1-SNAPSHOT.jar /home/gitlab-runner"
    - 'nohup java -jar /home/gitlab-runner/demo-0.0.1-SNAPSHOT.jar >> /home/gitlab-runner/demo.log 2>&1 &'
  only:
    - master